// Code generated by mtribes. DO NOT EDIT.

/* eslint-disable */
import { Collection } from '@mtribes/client-browser';

import NotificationExperience from '../experience/notificationExperience';

export default class NotificationColTempCollection extends Collection {
	constructor(id, childIds, broker) {
		super(id, broker, {
			id: 'Jo493Z0',
			t: 'c'
		});
		this.notification = new NotificationExperience(childIds[0], id, broker);
	}
}
