module.exports = {
    ADR: [
        'adr',
        {
            type: 'category',
            label: 'orca',
            items: [
                'orca/adr/serverless-vs-standalone-server',
                'orca/adr/session-management',
                'orca/adr/error-normalization',
                'orca/adr/logging',
                'orca/adr/session-management',
                'orca/adr/circuit-breakers',
                'orca/adr/service-error-tracking',
            ],
        },
        {
            type: 'category',
            label: 'web',
            items: [
                'web/adr/hello-test',
                'web/adr/hello-test_copy',
                'web/adr/modular-js-architecture',
                'web/adr/client-service-orchestration',
                'web/adr/modular-css-architecture',
                'web/adr/unit-tests',
                'web/adr/error-boundaries',
                'web/adr/component-explorer',
                'web/adr/modular-cli',
                'web/adr/routing',
                'web/adr/accessibility-auditing',
                'web/adr/deployments',
                'web/adr/releases',
                'web/adr/url-pathing',
                'web/adr/automation-qa-testing',
                'web/adr/state-management',
                'web/adr/local-server-http2-https',
                'web/adr/polyfills',
                'web/adr/navigation-menus',
                'web/adr/charting',
                'web/adr/drag-and-drop',
                'web/adr/dynamic-page-titles',
                'web/adr/page-title-structure',
                'web/adr/focus-styling',
                'web/adr/sub-resource-integrity-checks',
                'web/adr/mutation-patterns',
                'web/adr/mutation-concurrency',
                'web/adr/custom-drag-and-drop',
                'web/adr/page-validation',
                'web/adr/styling-approach-re-evaluation',
                'web/adr/content-security-policy',
                'web/adr/app-permissions',
                'web/adr/critical-page-errors',
                'web/adr/search-caching',
                'web/adr/component-optimization',
                'web/adr/general-performance-approach',
                'web/adr/static-asset-domain',
                'web/adr/development-auth',
                'web/adr/issueqa-auth',
                'web/adr/apollo-cache-ttl',
                'web/adr/accessiblility-auditing',
                'web/adr/i18n',
                'web/adr/automatic-persisted-queries',
                'web/adr/harness-deployments',
                'web/adr/state-rollback',
            ],
        },
    ],
}
