// Code generated by mtribes. DO NOT EDIT.

/* eslint-disable */
import { Experience } from '@mtribes/client-browser';

export default class MembercardexpExperience extends Experience {
	constructor(id, parentId, broker) {
		super(id, parentId, broker, {
			id: 'n0YwR3l',
			t: 'e',
			dataAlias: {
				'1': 'cardheight',
				'2': 'cardwidth'
			}
		});
		this.kind = 'MembercardexpExperience';
	}
}
