// Code generated by mtribes. DO NOT EDIT.

/* eslint-disable */
import { Experience } from '@mtribes/client-browser';

export default class NotificationExperience extends Experience {
	constructor(id, parentId, broker) {
		super(id, parentId, broker, {
			id: 'oyjGMQO',
			t: 'e',
			dataAlias: {
				'1': 'notificationColor',
				'2': 'notificationMessage'
			}
		});
		this.kind = 'NotificationExperience';
	}
}
