// Code generated by mtribes. DO NOT EDIT.

/* eslint-disable */
export const fallbacks = {
  v: 22749,
  json: '{"4M7M2po":{"on":true,"sid":"a6o6wJD","v":35906,"data":"{\\"1\\":\\"100px\\",\\"2\\":\\"200px\\"}"},"KVA9YAP":{"on":true,"sid":"gKAnE38","v":32271,"data":"{\\"1\\":{\\"opacity\\":1,\\"value\\":\\"#02b4f5\\"},\\"2\\":\\"Its a success\\"}"}}'
};
