// Code generated by mtribes. DO NOT EDIT.

/* eslint-disable */
import { Client, Broker } from '@mtribes/client-browser';
import { fallbacks } from './fallbacks';
import MembercardsCollection from './collection/membercardsCollection';
import NotificationColTempCollection from './collection/notificationColTempCollection';

export {
	Client,
	Session,
	SessionStatus,
	ChangeEventType,
	Experience,
	Section
} from '@mtribes/client-browser';

const broker = new Broker();
export const client = new Client('3fd8e53deee24b3ab97e7206e2c08123', fallbacks, broker);
export const session = client.session;

export const collections = {
	membercards: new MembercardsCollection('dapG0Aq', [
	'4M7M2po'
	], broker),
	notificationColTemp: new NotificationColTempCollection('mZ7xnAW', [
	'KVA9YAP'
	], broker),
};
